name: Auto Post to WordPress

on:
  schedule:
    # 매일 04:00, 10:00, 16:00(UTC) → KST 오후 1/7/1시
    - cron: '0 4,10,16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ───────── 랜덤 대기: 스케줄(run.event_name == 'schedule')일 때만 ─────────
      - name: Wait random time
        if: github.event_name == 'schedule'
        run: sleep $((RANDOM % 1800))

      - name: Run main script
        run: python run.py
